"""Remove responsable_entrega and notas_adicionales from project_entregaImplementaciones

Revision ID: 12c71a71d1d8
Revises: c863b98dda65
Create Date: 2025-10-14 07:46:41.058209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c71a71d1d8'
down_revision: Union[str, Sequence[str], None] = 'c863b98dda65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_entregaImplementaciones', 'responsable_entrega')
    op.drop_column('project_entregaImplementaciones', 'notas_adicionales')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_entregaImplementaciones', sa.Column('notas_adicionales', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('responsable_entrega', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
