"""create all project tables

Revision ID: 2988863cf59f
Revises: 
Create Date: 2025-10-02 09:54:03.116827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2988863cf59f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_campanas_clientes_corporativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_campanas_clientes_corporativos_id'), 'project_campanas_clientes_corporativos', ['id'], unique=False)
    op.create_index(op.f('ix_project_campanas_clientes_corporativos_nombre'), 'project_campanas_clientes_corporativos', ['nombre'], unique=False)
    op.create_table('project_equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_project_equipos_id'), 'project_equipos', ['id'], unique=False)
    op.create_table('project_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_estados_id'), 'project_estados', ['id'], unique=False)
    op.create_table('project_implementaciones_clienteimple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_implementacion', sa.String(), nullable=False),
    sa.Column('proceso_implementacion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_implementaciones_clienteimple_id'), 'project_implementaciones_clienteimple', ['id'], unique=False)
    op.create_table('project_prioridades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_prioridades_id'), 'project_prioridades', ['id'], unique=False)
    op.create_table('project_tipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_project_tipos_id'), 'project_tipos', ['id'], unique=False)
    op.create_table('project_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'usuario', name='rolusuario'), nullable=True),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_usuarios_correo'), 'project_usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_project_usuarios_id'), 'project_usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_project_usuarios_nombre'), 'project_usuarios', ['nombre'], unique=True)
    op.create_table('project_campanas_contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('cliente_corporativo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_corporativo_id'], ['project_campanas_clientes_corporativos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_campanas_contacto_id'), 'project_campanas_contacto', ['id'], unique=False)
    op.create_table('project_implementacion_contractual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_implementacion_id', sa.Integer(), nullable=False),
    sa.Column('modelo_contrato_seguimiento', sa.String(), nullable=True),
    sa.Column('modelo_contrato_estado', sa.String(), nullable=True),
    sa.Column('modelo_contrato_responsable', sa.String(), nullable=True),
    sa.Column('modelo_contrato_notas', sa.String(), nullable=True),
    sa.Column('modelo_confidencialidad_seguimiento', sa.String(), nullable=True),
    sa.Column('modelo_confidencialidad_estado', sa.String(), nullable=True),
    sa.Column('modelo_confidencialidad_responsable', sa.String(), nullable=True),
    sa.Column('modelo_confidencialidad_notas', sa.String(), nullable=True),
    sa.Column('alcance_seguimiento', sa.String(), nullable=True),
    sa.Column('alcance_estado', sa.String(), nullable=True),
    sa.Column('alcance_responsable', sa.String(), nullable=True),
    sa.Column('alcance_notas', sa.String(), nullable=True),
    sa.Column('fecha_inicio_seguimiento', sa.String(), nullable=True),
    sa.Column('fecha_inicio_estado', sa.String(), nullable=True),
    sa.Column('fecha_inicio_responsable', sa.String(), nullable=True),
    sa.Column('fecha_inicio_notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_implementacion_id'], ['project_implementaciones_clienteimple.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_implementacion_contractual_id'), 'project_implementacion_contractual', ['id'], unique=False)
    op.create_table('project_implementacion_procesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_implementacion_id', sa.Integer(), nullable=False),
    sa.Column('responsable_cliente_seguimiento', sa.String(), nullable=True),
    sa.Column('responsable_cliente_estado', sa.String(), nullable=True),
    sa.Column('responsable_cliente_responsable', sa.String(), nullable=True),
    sa.Column('responsable_cliente_notas', sa.String(), nullable=True),
    sa.Column('responsable_andes_seguimiento', sa.String(), nullable=True),
    sa.Column('responsable_andes_estado', sa.String(), nullable=True),
    sa.Column('responsable_andes_responsable', sa.String(), nullable=True),
    sa.Column('responsable_andes_notas', sa.String(), nullable=True),
    sa.Column('responsables_operacion_seguimiento', sa.String(), nullable=True),
    sa.Column('responsables_operacion_estado', sa.String(), nullable=True),
    sa.Column('responsables_operacion_responsable', sa.String(), nullable=True),
    sa.Column('responsables_operacion_notas', sa.String(), nullable=True),
    sa.Column('listado_reportes_seguimiento', sa.String(), nullable=True),
    sa.Column('listado_reportes_estado', sa.String(), nullable=True),
    sa.Column('listado_reportes_responsable', sa.String(), nullable=True),
    sa.Column('listado_reportes_notas', sa.String(), nullable=True),
    sa.Column('protocolo_comunicaciones_seguimiento', sa.String(), nullable=True),
    sa.Column('protocolo_comunicaciones_estado', sa.String(), nullable=True),
    sa.Column('protocolo_comunicaciones_responsable', sa.String(), nullable=True),
    sa.Column('protocolo_comunicaciones_notas', sa.String(), nullable=True),
    sa.Column('informacion_diaria_seguimiento', sa.String(), nullable=True),
    sa.Column('informacion_diaria_estado', sa.String(), nullable=True),
    sa.Column('informacion_diaria_responsable', sa.String(), nullable=True),
    sa.Column('informacion_diaria_notas', sa.String(), nullable=True),
    sa.Column('seguimiento_periodico_seguimiento', sa.String(), nullable=True),
    sa.Column('seguimiento_periodico_estado', sa.String(), nullable=True),
    sa.Column('seguimiento_periodico_responsable', sa.String(), nullable=True),
    sa.Column('seguimiento_periodico_notas', sa.String(), nullable=True),
    sa.Column('guiones_protocolos_seguimiento', sa.String(), nullable=True),
    sa.Column('guiones_protocolos_estado', sa.String(), nullable=True),
    sa.Column('guiones_protocolos_responsable', sa.String(), nullable=True),
    sa.Column('guiones_protocolos_notas', sa.String(), nullable=True),
    sa.Column('proceso_monitoreo_seguimiento', sa.String(), nullable=True),
    sa.Column('proceso_monitoreo_estado', sa.String(), nullable=True),
    sa.Column('proceso_monitoreo_responsable', sa.String(), nullable=True),
    sa.Column('proceso_monitoreo_notas', sa.String(), nullable=True),
    sa.Column('cronograma_tecnologia_seguimiento', sa.String(), nullable=True),
    sa.Column('cronograma_tecnologia_estado', sa.String(), nullable=True),
    sa.Column('cronograma_tecnologia_responsable', sa.String(), nullable=True),
    sa.Column('cronograma_tecnologia_notas', sa.String(), nullable=True),
    sa.Column('cronograma_capacitaciones_seguimiento', sa.String(), nullable=True),
    sa.Column('cronograma_capacitaciones_estado', sa.String(), nullable=True),
    sa.Column('cronograma_capacitaciones_responsable', sa.String(), nullable=True),
    sa.Column('cronograma_capacitaciones_notas', sa.String(), nullable=True),
    sa.Column('realizacion_pruebas_seguimiento', sa.String(), nullable=True),
    sa.Column('realizacion_pruebas_estado', sa.String(), nullable=True),
    sa.Column('realizacion_pruebas_responsable', sa.String(), nullable=True),
    sa.Column('realizacion_pruebas_notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_implementacion_id'], ['project_implementaciones_clienteimple.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_implementacion_procesos_id'), 'project_implementacion_procesos', ['id'], unique=False)
    op.create_table('project_implementacion_talentoHumano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_implementacion_id', sa.Integer(), nullable=False),
    sa.Column('perfil_personal_seguimiento', sa.String(), nullable=True),
    sa.Column('perfil_personal_estado', sa.String(), nullable=True),
    sa.Column('perfil_personal_responsable', sa.String(), nullable=True),
    sa.Column('perfil_personal_notas', sa.String(), nullable=True),
    sa.Column('cantidad_asesores_seguimiento', sa.String(), nullable=True),
    sa.Column('cantidad_asesores_estado', sa.String(), nullable=True),
    sa.Column('cantidad_asesores_responsable', sa.String(), nullable=True),
    sa.Column('cantidad_asesores_notas', sa.String(), nullable=True),
    sa.Column('horarios_seguimiento', sa.String(), nullable=True),
    sa.Column('horarios_estado', sa.String(), nullable=True),
    sa.Column('horarios_responsable', sa.String(), nullable=True),
    sa.Column('horarios_notas', sa.String(), nullable=True),
    sa.Column('formador_seguimiento', sa.String(), nullable=True),
    sa.Column('formador_estado', sa.String(), nullable=True),
    sa.Column('formador_responsable', sa.String(), nullable=True),
    sa.Column('formador_notas', sa.String(), nullable=True),
    sa.Column('capacitaciones_andes_seguimiento', sa.String(), nullable=True),
    sa.Column('capacitaciones_andes_estado', sa.String(), nullable=True),
    sa.Column('capacitaciones_andes_responsable', sa.String(), nullable=True),
    sa.Column('capacitaciones_andes_notas', sa.String(), nullable=True),
    sa.Column('capacitaciones_cliente_seguimiento', sa.String(), nullable=True),
    sa.Column('capacitaciones_cliente_estado', sa.String(), nullable=True),
    sa.Column('capacitaciones_cliente_responsable', sa.String(), nullable=True),
    sa.Column('capacitaciones_cliente_notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_implementacion_id'], ['project_implementaciones_clienteimple.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_implementacion_talentoHumano_id'), 'project_implementacion_talentoHumano', ['id'], unique=False)
    op.create_table('project_implementacion_tecnologia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_implementacion_id', sa.Integer(), nullable=False),
    sa.Column('creacion_modulo_seguimiento', sa.String(), nullable=True),
    sa.Column('creacion_modulo_estado', sa.String(), nullable=True),
    sa.Column('creacion_modulo_responsable', sa.String(), nullable=True),
    sa.Column('creacion_modulo_notas', sa.String(), nullable=True),
    sa.Column('tipificacion_interacciones_seguimiento', sa.String(), nullable=True),
    sa.Column('tipificacion_interacciones_estado', sa.String(), nullable=True),
    sa.Column('tipificacion_interacciones_responsable', sa.String(), nullable=True),
    sa.Column('tipificacion_interacciones_notas', sa.String(), nullable=True),
    sa.Column('aplicativos_proceso_seguimiento', sa.String(), nullable=True),
    sa.Column('aplicativos_proceso_estado', sa.String(), nullable=True),
    sa.Column('aplicativos_proceso_responsable', sa.String(), nullable=True),
    sa.Column('aplicativos_proceso_notas', sa.String(), nullable=True),
    sa.Column('whatsapp_seguimiento', sa.String(), nullable=True),
    sa.Column('whatsapp_estado', sa.String(), nullable=True),
    sa.Column('whatsapp_responsable', sa.String(), nullable=True),
    sa.Column('whatsapp_notas', sa.String(), nullable=True),
    sa.Column('correos_electronicos_seguimiento', sa.String(), nullable=True),
    sa.Column('correos_electronicos_estado', sa.String(), nullable=True),
    sa.Column('correos_electronicos_responsable', sa.String(), nullable=True),
    sa.Column('correos_electronicos_notas', sa.String(), nullable=True),
    sa.Column('requisitos_grabacion_seguimiento', sa.String(), nullable=True),
    sa.Column('requisitos_grabacion_estado', sa.String(), nullable=True),
    sa.Column('requisitos_grabacion_responsable', sa.String(), nullable=True),
    sa.Column('requisitos_grabacion_notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_implementacion_id'], ['project_implementaciones_clienteimple.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_implementacion_tecnologia_id'), 'project_implementacion_tecnologia', ['id'], unique=False)
    op.create_table('project_proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('enlace', sa.String(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('progreso', sa.Float(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('prioridad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['project_estados.id'], ),
    sa.ForeignKeyConstraint(['prioridad_id'], ['project_prioridades.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['project_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_proyectos_id'), 'project_proyectos', ['id'], unique=False)
    op.create_table('project_campanas_campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('SAC', 'TMC', 'TVT', 'CBZ', name='tipocampaña'), nullable=False),
    sa.Column('cliente_corporativo_id', sa.Integer(), nullable=False),
    sa.Column('contacto_id', sa.Integer(), nullable=False),
    sa.Column('contacto_id_secundario', sa.Integer(), nullable=True),
    sa.Column('lider_de_campaña', sa.String(), nullable=False),
    sa.Column('ejecutivo', sa.String(), nullable=False),
    sa.Column('fecha_de_produccion', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estadocampaña'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_corporativo_id'], ['project_campanas_clientes_corporativos.id'], ),
    sa.ForeignKeyConstraint(['contacto_id'], ['project_campanas_contacto.id'], ),
    sa.ForeignKeyConstraint(['contacto_id_secundario'], ['project_campanas_contacto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_campanas_campanas_id'), 'project_campanas_campanas', ['id'], unique=False)
    op.create_table('project_tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['project_proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyecto_equipos',
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['project_equipos.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['project_proyectos.id'], ),
    sa.PrimaryKeyConstraint('proyecto_id', 'equipo_id')
    )
    op.create_table('proyecto_tipos',
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['project_proyectos.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['project_tipos.id'], ),
    sa.PrimaryKeyConstraint('proyecto_id', 'tipo_id')
    )
    op.create_table('project_facturacion_campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaña_id', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('periodicidad', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaña_id'], ['project_campanas_campanas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_facturacion_campanas_id'), 'project_facturacion_campanas', ['id'], unique=False)
    op.create_table('project_historial_campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaña_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('cambios', sa.JSON(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaña_id'], ['project_campanas_campanas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_historial_campanas_id'), 'project_historial_campanas', ['id'], unique=False)
    op.create_table('project_productos_campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaña_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PRODUCTO', 'SERVICIO', name='tipoproducto'), nullable=False),
    sa.Column('producto_servicio', sa.String(), nullable=False),
    sa.Column('proveedor', sa.String(), nullable=False),
    sa.Column('propiedad', sa.Enum('PROPIA', 'ALQUILADA', name='propiedadproducto'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaña_id'], ['project_campanas_campanas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_productos_campanas_id'), 'project_productos_campanas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_productos_campanas_id'), table_name='project_productos_campanas')
    op.drop_table('project_productos_campanas')
    op.drop_index(op.f('ix_project_historial_campanas_id'), table_name='project_historial_campanas')
    op.drop_table('project_historial_campanas')
    op.drop_index(op.f('ix_project_facturacion_campanas_id'), table_name='project_facturacion_campanas')
    op.drop_table('project_facturacion_campanas')
    op.drop_table('proyecto_tipos')
    op.drop_table('proyecto_equipos')
    op.drop_table('project_tareas')
    op.drop_index(op.f('ix_project_campanas_campanas_id'), table_name='project_campanas_campanas')
    op.drop_table('project_campanas_campanas')
    op.drop_index(op.f('ix_project_proyectos_id'), table_name='project_proyectos')
    op.drop_table('project_proyectos')
    op.drop_index(op.f('ix_project_implementacion_tecnologia_id'), table_name='project_implementacion_tecnologia')
    op.drop_table('project_implementacion_tecnologia')
    op.drop_index(op.f('ix_project_implementacion_talentoHumano_id'), table_name='project_implementacion_talentoHumano')
    op.drop_table('project_implementacion_talentoHumano')
    op.drop_index(op.f('ix_project_implementacion_procesos_id'), table_name='project_implementacion_procesos')
    op.drop_table('project_implementacion_procesos')
    op.drop_index(op.f('ix_project_implementacion_contractual_id'), table_name='project_implementacion_contractual')
    op.drop_table('project_implementacion_contractual')
    op.drop_index(op.f('ix_project_campanas_contacto_id'), table_name='project_campanas_contacto')
    op.drop_table('project_campanas_contacto')
    op.drop_index(op.f('ix_project_usuarios_nombre'), table_name='project_usuarios')
    op.drop_index(op.f('ix_project_usuarios_id'), table_name='project_usuarios')
    op.drop_index(op.f('ix_project_usuarios_correo'), table_name='project_usuarios')
    op.drop_table('project_usuarios')
    op.drop_index(op.f('ix_project_tipos_id'), table_name='project_tipos')
    op.drop_table('project_tipos')
    op.drop_index(op.f('ix_project_prioridades_id'), table_name='project_prioridades')
    op.drop_table('project_prioridades')
    op.drop_index(op.f('ix_project_implementaciones_clienteimple_id'), table_name='project_implementaciones_clienteimple')
    op.drop_table('project_implementaciones_clienteimple')
    op.drop_index(op.f('ix_project_estados_id'), table_name='project_estados')
    op.drop_table('project_estados')
    op.drop_index(op.f('ix_project_equipos_id'), table_name='project_equipos')
    op.drop_table('project_equipos')
    op.drop_index(op.f('ix_project_campanas_clientes_corporativos_nombre'), table_name='project_campanas_clientes_corporativos')
    op.drop_index(op.f('ix_project_campanas_clientes_corporativos_id'), table_name='project_campanas_clientes_corporativos')
    op.drop_table('project_campanas_clientes_corporativos')
    # ### end Alembic commands ###
