"""empty message

Revision ID: 2a1b0d9acf50
Revises: 
Create Date: 2025-07-22 11:31:19.655297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1b0d9acf50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campañas_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('empresa', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('contacto_principal', sa.String(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campañas_clientes_id'), 'campañas_clientes', ['id'], unique=False)
    op.create_table('project_equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_project_equipos_id'), 'project_equipos', ['id'], unique=False)
    op.create_table('project_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_estados_id'), 'project_estados', ['id'], unique=False)
    op.create_table('project_prioridades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_prioridades_id'), 'project_prioridades', ['id'], unique=False)
    op.create_table('project_tipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_project_tipos_id'), 'project_tipos', ['id'], unique=False)
    op.create_table('project_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'usuario', name='rolusuario'), nullable=True),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_usuarios_correo'), 'project_usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_project_usuarios_id'), 'project_usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_project_usuarios_nombre'), 'project_usuarios', ['nombre'], unique=True)
    op.create_table('campañas_campañas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('SAC', 'TMG', 'CBI', 'OTRO', name='tipocampaña'), nullable=False),
    sa.Column('cje', sa.String(), nullable=True),
    sa.Column('lider', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('presupuesto', sa.String(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['campañas_clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campañas_campañas_id'), 'campañas_campañas', ['id'], unique=False)
    op.create_table('project_proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('enlace', sa.String(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('progreso', sa.Float(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('prioridad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['project_estados.id'], ),
    sa.ForeignKeyConstraint(['prioridad_id'], ['project_prioridades.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['project_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_proyectos_id'), 'project_proyectos', ['id'], unique=False)
    op.create_table('project_tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['project_proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyecto_equipos',
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['project_equipos.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['project_proyectos.id'], ),
    sa.PrimaryKeyConstraint('proyecto_id', 'equipo_id')
    )
    op.create_table('proyecto_tipos',
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['project_proyectos.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['project_tipos.id'], ),
    sa.PrimaryKeyConstraint('proyecto_id', 'tipo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proyecto_tipos')
    op.drop_table('proyecto_equipos')
    op.drop_table('project_tareas')
    op.drop_index(op.f('ix_project_proyectos_id'), table_name='project_proyectos')
    op.drop_table('project_proyectos')
    op.drop_index(op.f('ix_campañas_campañas_id'), table_name='campañas_campañas')
    op.drop_table('campañas_campañas')
    op.drop_index(op.f('ix_project_usuarios_nombre'), table_name='project_usuarios')
    op.drop_index(op.f('ix_project_usuarios_id'), table_name='project_usuarios')
    op.drop_index(op.f('ix_project_usuarios_correo'), table_name='project_usuarios')
    op.drop_table('project_usuarios')
    op.drop_index(op.f('ix_project_tipos_id'), table_name='project_tipos')
    op.drop_table('project_tipos')
    op.drop_index(op.f('ix_project_prioridades_id'), table_name='project_prioridades')
    op.drop_table('project_prioridades')
    op.drop_index(op.f('ix_project_estados_id'), table_name='project_estados')
    op.drop_table('project_estados')
    op.drop_index(op.f('ix_project_equipos_id'), table_name='project_equipos')
    op.drop_table('project_equipos')
    op.drop_index(op.f('ix_campañas_clientes_id'), table_name='campañas_clientes')
    op.drop_table('campañas_clientes')
    # ### end Alembic commands ###
