"""add contacto_id and contacto_id_secundario to project_campanias

Revision ID: 463d5cb8cf7e
Revises: 2988863cf59f
Create Date: 2025-10-02 10:24:46.841314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463d5cb8cf7e'
down_revision: Union[str, Sequence[str], None] = '2988863cf59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
