"""remove_unused_json_columns_from_implementaciones

Revision ID: 4f350724156b
Revises: 6f698bccbe57
Create Date: 2025-10-03 11:06:57.014544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f350724156b'
down_revision: Union[str, Sequence[str], None] = '6f698bccbe57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_implementaciones_clienteimple', sa.Column('contractual', sa.JSON(), nullable=True))
    op.add_column('project_implementaciones_clienteimple', sa.Column('talento_humano', sa.JSON(), nullable=True))
    op.add_column('project_implementaciones_clienteimple', sa.Column('procesos', sa.JSON(), nullable=True))
    op.add_column('project_implementaciones_clienteimple', sa.Column('tecnologia', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_implementaciones_clienteimple', 'tecnologia')
    op.drop_column('project_implementaciones_clienteimple', 'procesos')
    op.drop_column('project_implementaciones_clienteimple', 'talento_humano')
    op.drop_column('project_implementaciones_clienteimple', 'contractual')
    # ### end Alembic commands ###
