"""create_project_entregaImplementaciones_table

Revision ID: 52808178d974
Revises: 9c942b8ef46f
Create Date: 2025-10-14 07:31:11.288955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "52808178d974"
down_revision: Union[str, Sequence[str], None] = "9c942b8ef46f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_entregaImplementaciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("implementacion_id", sa.Integer(), nullable=False),
        sa.Column("fecha_entrega", sa.DateTime(), nullable=False),
        sa.Column("datos_entrega", sa.JSON(), nullable=True),
        sa.Column("responsable_entrega", sa.String(length=255), nullable=True),
        sa.Column("estado_entrega", sa.String(length=50), nullable=False),
        sa.Column("notas_adicionales", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["implementacion_id"],
            ["project_implementaciones_clienteimple.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_entregaImplementaciones_id"),
        "project_entregaImplementaciones",
        ["id"],
        unique=False,
    )
    op.drop_index("ix_entregas_id", table_name="entregas")
    op.drop_table("entregas")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entregas",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "implementacion_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "cliente", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "servicio", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "fecha_entrega", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("estado", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "responsable", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "datos_contractual",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "datos_tecnologia",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "datos_procesos",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("notas", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["implementacion_id"],
            ["project_implementaciones_clienteimple.id"],
            name="entregas_implementacion_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="entregas_pkey"),
    )
    op.create_index("ix_entregas_id", "entregas", ["id"], unique=False)
    op.drop_index(
        op.f("ix_project_entregaImplementaciones_id"),
        table_name="project_entregaImplementaciones",
    )
    op.drop_table("project_entregaImplementaciones")
    # ### end Alembic commands ###
