"""Add historial campañas

Revision ID: 62c257080cd3
Revises: 
Create Date: 2025-07-25 07:55:49.702925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c257080cd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_campañas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaña_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('cambios', sa.JSON(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaña_id'], ['campañas_campañas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_campañas_id'), 'historial_campañas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_campañas_id'), table_name='historial_campañas')
    op.drop_table('historial_campañas')
    # ### end Alembic commands ###
