"""Agrega campo estado a implementaciones

Revision ID: 6f698bccbe57
Revises: d9a904263f05
Create Date: 2025-10-02 12:24:31.072790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f698bccbe57"
down_revision: Union[str, Sequence[str], None] = "d9a904263f05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_implementaciones_clienteimple",
        sa.Column("estado", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_implementaciones_clienteimple", "estado")
    # ### end Alembic commands ###
