"""Agrega columnas cliente y demás a implementaciones

Revision ID: 732690e104bb
Revises: 6b83debdc419
Create Date: 2025-10-02 12:18:32.773877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732690e104bb'
down_revision: Union[str, Sequence[str], None] = '6b83debdc419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_implementaciones_clienteimple', sa.Column('cliente', sa.String(), nullable=False))
    op.add_column('project_implementaciones_clienteimple', sa.Column('proceso', sa.String(), nullable=False))
    op.add_column('project_implementaciones_clienteimple', sa.Column('contractual', sa.JSON(), nullable=True))
    op.add_column('project_implementaciones_clienteimple', sa.Column('talento_humano', sa.JSON(), nullable=True))
    op.add_column('project_implementaciones_clienteimple', sa.Column('procesos', sa.JSON(), nullable=True))
    op.add_column('project_implementaciones_clienteimple', sa.Column('tecnologia', sa.JSON(), nullable=True))
    op.add_column('project_implementaciones_clienteimple', sa.Column('estado', sa.String(), nullable=True))
    op.drop_column('project_implementaciones_clienteimple', 'proceso_implementacion')
    op.drop_column('project_implementaciones_clienteimple', 'cliente_implementacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_implementaciones_clienteimple', sa.Column('cliente_implementacion', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('project_implementaciones_clienteimple', sa.Column('proceso_implementacion', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('project_implementaciones_clienteimple', 'estado')
    op.drop_column('project_implementaciones_clienteimple', 'tecnologia')
    op.drop_column('project_implementaciones_clienteimple', 'procesos')
    op.drop_column('project_implementaciones_clienteimple', 'talento_humano')
    op.drop_column('project_implementaciones_clienteimple', 'contractual')
    op.drop_column('project_implementaciones_clienteimple', 'proceso')
    op.drop_column('project_implementaciones_clienteimple', 'cliente')
    # ### end Alembic commands ###
