"""add contacto_id and contacto_id_secundario to project_campanias

Revision ID: 886bd78d7b4a
Revises: 463d5cb8cf7e
Create Date: 2025-10-02 10:25:34.665615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886bd78d7b4a'
down_revision: Union[str, Sequence[str], None] = '463d5cb8cf7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
