"""create_entregas_table

Revision ID: 9c942b8ef46f
Revises: 4f350724156b
Create Date: 2025-10-10 10:02:10.150424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c942b8ef46f'
down_revision: Union[str, Sequence[str], None] = '4f350724156b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('implementacion_id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=255), nullable=False),
    sa.Column('servicio', sa.String(length=255), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('responsable', sa.String(length=255), nullable=True),
    sa.Column('datos_contractual', sa.JSON(), nullable=True),
    sa.Column('datos_tecnologia', sa.JSON(), nullable=True),
    sa.Column('datos_procesos', sa.JSON(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['implementacion_id'], ['project_implementaciones_clienteimple.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entregas_id'), 'entregas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entregas_id'), table_name='entregas')
    op.drop_table('entregas')
    # ### end Alembic commands ###
