"""crear_tablas_productos_y_facturacion

Revision ID: ad7339572720
Revises: 3f169d713e50
Create Date: 2025-07-25 10:17:45.962073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7339572720'
down_revision: Union[str, Sequence[str], None] = '3f169d713e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturacion_campañas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaña_id', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaña_id'], ['campañas_campañas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturacion_campañas_id'), 'facturacion_campañas', ['id'], unique=False)
    op.create_table('productos_campañas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaña_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PRODUCTO', 'SERVICIO', name='tipoproducto'), nullable=False),
    sa.Column('proveedor', sa.String(), nullable=False),
    sa.Column('propiedad', sa.Enum('PROPIA', 'ALQUILADA', name='propiedadproducto'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaña_id'], ['campañas_campañas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_campañas_id'), 'productos_campañas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_campañas_id'), table_name='productos_campañas')
    op.drop_table('productos_campañas')
    op.drop_index(op.f('ix_facturacion_campañas_id'), table_name='facturacion_campañas')
    op.drop_table('facturacion_campañas')
    # ### end Alembic commands ###
