"""Agregar producto_servicio y periodicidad

Revision ID: b8780dd64820
Revises: ad7339572720
Create Date: 2025-07-25 11:48:09.399449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8780dd64820'
down_revision: Union[str, Sequence[str], None] = 'ad7339572720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columnas como nullable primero
    op.add_column('facturacion_campañas', sa.Column('periodicidad', sa.String(), nullable=True))
    op.add_column('productos_campañas', sa.Column('producto_servicio', sa.String(), nullable=True))
    
    # Actualizar registros existentes con valores por defecto
    op.execute("UPDATE productos_campañas SET producto_servicio = 'Sin especificar' WHERE producto_servicio IS NULL")
    op.execute("UPDATE facturacion_campañas SET periodicidad = 'Mensual' WHERE periodicidad IS NULL")
    
    # Hacer las columnas NOT NULL después de agregar valores por defecto
    op.alter_column('productos_campañas', 'producto_servicio', nullable=False)
    op.alter_column('facturacion_campañas', 'periodicidad', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos_campañas', 'producto_servicio')
    op.drop_column('facturacion_campañas', 'periodicidad')
    # ### end Alembic commands ###
