"""add new prefixed tables

Revision ID: c746292298a2
Revises: 
Create Date: 2025-08-01 10:11:58.056814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c746292298a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanas_clientes_corporativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campanas_clientes_corporativos_id'), 'campanas_clientes_corporativos', ['id'], unique=False)
    op.create_index(op.f('ix_campanas_clientes_corporativos_nombre'), 'campanas_clientes_corporativos', ['nombre'], unique=False)
    op.create_table('project_equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_project_equipos_id'), 'project_equipos', ['id'], unique=False)
    op.create_table('project_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_estados_id'), 'project_estados', ['id'], unique=False)
    op.create_table('project_prioridades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_prioridades_id'), 'project_prioridades', ['id'], unique=False)
    op.create_table('project_tipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_project_tipos_id'), 'project_tipos', ['id'], unique=False)
    op.create_table('project_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'usuario', name='rolusuario'), nullable=True),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_usuarios_correo'), 'project_usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_project_usuarios_id'), 'project_usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_project_usuarios_nombre'), 'project_usuarios', ['nombre'], unique=True)
    op.create_table('campanas_contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('cliente_corporativo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_corporativo_id'], ['campanas_clientes_corporativos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campanas_contacto_id'), 'campanas_contacto', ['id'], unique=False)
    op.create_table('project_proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('enlace', sa.String(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('progreso', sa.Float(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('prioridad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['project_estados.id'], ),
    sa.ForeignKeyConstraint(['prioridad_id'], ['project_prioridades.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['project_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_proyectos_id'), 'project_proyectos', ['id'], unique=False)
    op.create_table('campanas_campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('SAC', 'TMC', 'TVT', 'CBZ', name='tipocampaña'), nullable=False),
    sa.Column('cliente_corporativo_id', sa.Integer(), nullable=False),
    sa.Column('contacto_id', sa.Integer(), nullable=False),
    sa.Column('contacto_id_secundario', sa.Integer(), nullable=True),
    sa.Column('lider_de_campaña', sa.String(), nullable=False),
    sa.Column('ejecutivo', sa.String(), nullable=False),
    sa.Column('fecha_de_produccion', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estadocampaña'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_corporativo_id'], ['campanas_clientes_corporativos.id'], ),
    sa.ForeignKeyConstraint(['contacto_id'], ['campanas_contacto.id'], ),
    sa.ForeignKeyConstraint(['contacto_id_secundario'], ['campanas_contacto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campanas_campanas_id'), 'campanas_campanas', ['id'], unique=False)
    op.create_table('project_tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['project_proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyecto_equipos',
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['project_equipos.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['project_proyectos.id'], ),
    sa.PrimaryKeyConstraint('proyecto_id', 'equipo_id')
    )
    op.create_table('proyecto_tipos',
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['project_proyectos.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['project_tipos.id'], ),
    sa.PrimaryKeyConstraint('proyecto_id', 'tipo_id')
    )
    op.create_table('facturacion_campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaña_id', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('periodicidad', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaña_id'], ['campanas_campanas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturacion_campanas_id'), 'facturacion_campanas', ['id'], unique=False)
    op.create_table('historial_campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaña_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('cambios', sa.JSON(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaña_id'], ['campanas_campanas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_campanas_id'), 'historial_campanas', ['id'], unique=False)
    op.create_table('productos_campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaña_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PRODUCTO', 'SERVICIO', name='tipoproducto'), nullable=False),
    sa.Column('producto_servicio', sa.String(), nullable=False),
    sa.Column('proveedor', sa.String(), nullable=False),
    sa.Column('propiedad', sa.Enum('PROPIA', 'ALQUILADA', name='propiedadproducto'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaña_id'], ['campanas_campanas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_campanas_id'), 'productos_campanas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrade omitted for safety: no destructive operations
    # ### end Alembic commands ###
