"""update_entrega_table_with_individual_columns

Revision ID: c863b98dda65
Revises: 52808178d974
Create Date: 2025-10-14 07:40:11.911842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c863b98dda65'
down_revision: Union[str, Sequence[str], None] = '52808178d974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_entregaImplementaciones', sa.Column('contrato', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('acuerdo_niveles_servicio', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('polizas', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('penalidades', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('alcance_servicio', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('unidades_facturacion', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('acuerdo_pago', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('incremento', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('mapa_aplicativos', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('internet', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('telefonia', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('whatsapp', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('integraciones', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('vpn', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('diseno_ivr', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('transferencia_llamadas', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('correos_electronicos', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('linea_018000', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('linea_entrada', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('sms', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('requisitos_grabacion', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('entrega_resguardo', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('encuesta_satisfaccion', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('listado_reportes', sa.Text(), nullable=True))
    op.add_column('project_entregaImplementaciones', sa.Column('proceso_monitoreo_calidad', sa.Text(), nullable=True))
    op.drop_column('project_entregaImplementaciones', 'datos_entrega')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_entregaImplementaciones', sa.Column('datos_entrega', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('project_entregaImplementaciones', 'proceso_monitoreo_calidad')
    op.drop_column('project_entregaImplementaciones', 'listado_reportes')
    op.drop_column('project_entregaImplementaciones', 'encuesta_satisfaccion')
    op.drop_column('project_entregaImplementaciones', 'entrega_resguardo')
    op.drop_column('project_entregaImplementaciones', 'requisitos_grabacion')
    op.drop_column('project_entregaImplementaciones', 'sms')
    op.drop_column('project_entregaImplementaciones', 'linea_entrada')
    op.drop_column('project_entregaImplementaciones', 'linea_018000')
    op.drop_column('project_entregaImplementaciones', 'correos_electronicos')
    op.drop_column('project_entregaImplementaciones', 'transferencia_llamadas')
    op.drop_column('project_entregaImplementaciones', 'diseno_ivr')
    op.drop_column('project_entregaImplementaciones', 'vpn')
    op.drop_column('project_entregaImplementaciones', 'integraciones')
    op.drop_column('project_entregaImplementaciones', 'whatsapp')
    op.drop_column('project_entregaImplementaciones', 'telefonia')
    op.drop_column('project_entregaImplementaciones', 'internet')
    op.drop_column('project_entregaImplementaciones', 'mapa_aplicativos')
    op.drop_column('project_entregaImplementaciones', 'incremento')
    op.drop_column('project_entregaImplementaciones', 'acuerdo_pago')
    op.drop_column('project_entregaImplementaciones', 'unidades_facturacion')
    op.drop_column('project_entregaImplementaciones', 'alcance_servicio')
    op.drop_column('project_entregaImplementaciones', 'penalidades')
    op.drop_column('project_entregaImplementaciones', 'polizas')
    op.drop_column('project_entregaImplementaciones', 'acuerdo_niveles_servicio')
    op.drop_column('project_entregaImplementaciones', 'contrato')
    # ### end Alembic commands ###
