"""empty message

Revision ID: d9a904263f05
Revises: 732690e104bb
Create Date: 2025-10-02 12:19:38.631307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d9a904263f05"
down_revision: Union[str, Sequence[str], None] = "732690e104bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_implementaciones_clienteimple", "procesos")
    op.drop_column("project_implementaciones_clienteimple", "contractual")
    op.drop_column("project_implementaciones_clienteimple", "talento_humano")
    op.drop_column("project_implementaciones_clienteimple", "tecnologia")
    op.drop_column("project_implementaciones_clienteimple", "estado")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_implementaciones_clienteimple",
        sa.Column("estado", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "project_implementaciones_clienteimple",
        sa.Column(
            "tecnologia",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "project_implementaciones_clienteimple",
        sa.Column(
            "talento_humano",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "project_implementaciones_clienteimple",
        sa.Column(
            "contractual",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "project_implementaciones_clienteimple",
        sa.Column(
            "procesos",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
