"""actualizar tipos campaña

Revision ID: update_campaign_types
Revises: c51948fcbc5e
Create Date: 2025-07-22 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'update_campaign_types'
down_revision: Union[str, Sequence[str], None] = 'c51948fcbc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Primero, cambiar temporalmente la columna a texto
    op.execute("ALTER TABLE campañas_campañas ALTER COLUMN tipo TYPE TEXT")
    
    # Eliminar el enum viejo
    op.execute("DROP TYPE IF EXISTS tipocampaña")
    
    # Crear el nuevo enum con los valores correctos
    op.execute("CREATE TYPE tipocampaña AS ENUM ('SAC', 'TMC', 'TVT', 'CBZ')")
    
    # Actualizar los datos existentes
    op.execute("UPDATE campañas_campañas SET tipo = 'TMC' WHERE tipo = 'TMG'")
    op.execute("UPDATE campañas_campañas SET tipo = 'CBZ' WHERE tipo = 'CBI'")
    op.execute("UPDATE campañas_campañas SET tipo = 'TVT' WHERE tipo = 'OTRO'")
    
    # Cambiar la columna de vuelta al enum
    op.execute("ALTER TABLE campañas_campañas ALTER COLUMN tipo TYPE tipocampaña USING tipo::tipocampaña")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Cambiar temporalmente la columna a texto
    op.execute("ALTER TABLE campañas_campañas ALTER COLUMN tipo TYPE TEXT")
    
    # Eliminar el enum nuevo
    op.execute("DROP TYPE IF EXISTS tipocampaña")
    
    # Crear el enum viejo
    op.execute("CREATE TYPE tipocampaña AS ENUM ('SAC', 'TMG', 'CBI', 'OTRO')")
    
    # Actualizar los datos de vuelta
    op.execute("UPDATE campañas_campañas SET tipo = 'TMG' WHERE tipo = 'TMC'")
    op.execute("UPDATE campañas_campañas SET tipo = 'CBI' WHERE tipo = 'CBZ'")
    op.execute("UPDATE campañas_campañas SET tipo = 'OTRO' WHERE tipo = 'TVT'")
    
    # Cambiar la columna de vuelta al enum
    op.execute("ALTER TABLE campañas_campañas ALTER COLUMN tipo TYPE tipocampaña USING tipo::tipocampaña")
    
    # ### end Alembic commands ###
