from sqlalchemy import Column, Integer, String, ForeignKey
from core.database import Base


class ProjectImplementacionProcesos(Base):
    __tablename__ = "project_implementacion_procesos"
    id = Column(Integer, primary_key=True, index=True)
    cliente_implementacion_id = Column(
        Integer, ForeignKey("project_implementaciones_clienteimple.id"), nullable=False
    )
    responsable_cliente_seguimiento = Column(String)
    responsable_cliente_estado = Column(String)
    responsable_cliente_responsable = Column(String)
    responsable_cliente_notas = Column(String)
    responsable_andes_seguimiento = Column(String)
    responsable_andes_estado = Column(String)
    responsable_andes_responsable = Column(String)
    responsable_andes_notas = Column(String)
    responsables_operacion_seguimiento = Column(String)
    responsables_operacion_estado = Column(String)
    responsables_operacion_responsable = Column(String)
    responsables_operacion_notas = Column(String)
    listado_reportes_seguimiento = Column(String)
    listado_reportes_estado = Column(String)
    listado_reportes_responsable = Column(String)
    listado_reportes_notas = Column(String)
    protocolo_comunicaciones_seguimiento = Column(String)
    protocolo_comunicaciones_estado = Column(String)
    protocolo_comunicaciones_responsable = Column(String)
    protocolo_comunicaciones_notas = Column(String)
    informacion_diaria_seguimiento = Column(String)
    informacion_diaria_estado = Column(String)
    informacion_diaria_responsable = Column(String)
    informacion_diaria_notas = Column(String)
    seguimiento_periodico_seguimiento = Column(String)
    seguimiento_periodico_estado = Column(String)
    seguimiento_periodico_responsable = Column(String)
    seguimiento_periodico_notas = Column(String)
    guiones_protocolos_seguimiento = Column(String)
    guiones_protocolos_estado = Column(String)
    guiones_protocolos_responsable = Column(String)
    guiones_protocolos_notas = Column(String)
    proceso_monitoreo_seguimiento = Column(String)
    proceso_monitoreo_estado = Column(String)
    proceso_monitoreo_responsable = Column(String)
    proceso_monitoreo_notas = Column(String)
    cronograma_tecnologia_seguimiento = Column(String)
    cronograma_tecnologia_estado = Column(String)
    cronograma_tecnologia_responsable = Column(String)
    cronograma_tecnologia_notas = Column(String)
    cronograma_capacitaciones_seguimiento = Column(String)
    cronograma_capacitaciones_estado = Column(String)
    cronograma_capacitaciones_responsable = Column(String)
    cronograma_capacitaciones_notas = Column(String)
    realizacion_pruebas_seguimiento = Column(String)
    realizacion_pruebas_estado = Column(String)
    realizacion_pruebas_responsable = Column(String)
    realizacion_pruebas_notas = Column(String)
